
CREATE DATABASE IF NOT EXISTS gerkatin;
USE gerkatin;

CREATE TABLE IF NOT EXISTS slider (
  id INT AUTO_INCREMENT PRIMARY KEY,
  gambar VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS video (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(255),
  file VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS berita (
  id INT AUTO_INCREMENT PRIMARY KEY,
  judul VARCHAR(255),
  ringkasan TEXT,
  isi TEXT,
  gambar VARCHAR(255)
);
